version: "3.8"
services:
  database:
    container_name: local_mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin","ping","-h","localhost" ]
      timeout: 20s
      retries: 10
  career_startup:
    container_name: career_startup
    build: ./
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://local_mysql/career_startup
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: p@ssword
      SPRING_FLYWAY_URL: jdbc:mysql://local_mysql/career_startup
      SPRING_FLYWAY_USER: admin
      SPRING_FLYWAY_PASSWORD: p@ssword
    depends_on:
      database:
        condition: service_healthy
